// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJlb-E1s2fpECZOCFuFDcCP8jMtkR9l5E',
    appId: '1:1030401473400:web:09b6053db7575ca9d4668d',
    messagingSenderId: '1030401473400',
    projectId: 'archinest-5d0b7',
    authDomain: 'archinest-5d0b7.firebaseapp.com',
    storageBucket: 'archinest-5d0b7.firebasestorage.app',
    measurementId: 'G-XVEEH7NGJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5slu3T8R6poNsBU1GxsZaD6L6-DJqHM',
    appId: '1:1030401473400:android:2616aa4ad529cecfd4668d',
    messagingSenderId: '1030401473400',
    projectId: 'archinest-5d0b7',
    storageBucket: 'archinest-5d0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLgtFsoAjQDelOI6IMruBzaOUdEzaTlU',
    appId: '1:1030401473400:ios:601adeaabbc79d19d4668d',
    messagingSenderId: '1030401473400',
    projectId: 'archinest-5d0b7',
    storageBucket: 'archinest-5d0b7.firebasestorage.app',
    iosBundleId: 'com.interiordesign.interiorDesignApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLgtFsoAjQDelOI6IMruBzaOUdEzaTlU',
    appId: '1:1030401473400:ios:601adeaabbc79d19d4668d',
    messagingSenderId: '1030401473400',
    projectId: 'archinest-5d0b7',
    storageBucket: 'archinest-5d0b7.firebasestorage.app',
    iosBundleId: 'com.interiordesign.interiorDesignApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJlb-E1s2fpECZOCFuFDcCP8jMtkR9l5E',
    appId: '1:1030401473400:web:dc77124db3ba5cddd4668d',
    messagingSenderId: '1030401473400',
    projectId: 'archinest-5d0b7',
    authDomain: 'archinest-5d0b7.firebaseapp.com',
    storageBucket: 'archinest-5d0b7.firebasestorage.app',
    measurementId: 'G-DWLP97Q00L',
  );
}
